--- 
output_dir: output
data_sources: 
- type: filesystem_unified
  items_root: /
  layouts_root: /

# Custom settings

# Use rsync + ssh for live site. To deploy:
#
#   % rake deploy:rsync
deploy:
  default:
    dst: "meedan.net:www/qfi"
    options: ['-ave ssh', '--exclude=.DS_Store', '--exclude=*~']

# domain to which this site is deployed
base_url: http://qfi.meedan.net

# currently used by logo
site_name: QFI Teacher Dashboard

# number of full featured posts to display on front
featured_count: 0
# number of excerpted posts to display on front
excerpt_count: 30

# number of other articles to reference at bottom of each article
other_articles_max: 0

# DISQUS Site Shortname. Comment out to disable.
disqus_shortname: qfi-teachers